### ISSUE TITLE
Depot Labels disappear from depot and shows as huge label in the middle of the screen.

### ISSUE THREAD

**Issue by Bryku1978** [akarnokd/plan-b-terraform-mods#8] opened 2023-02-19 14:45 UTC
![image](https://user-images.githubusercontent.com/125812369/219955439-9e12a2d2-15d1-4627-be04-5263780ae510.png)

**Comment by akarnokd** [comment] 2023-02-19 15:29
Is there a problem?

**Comment by akarnokd** [comment] 2023-02-19 15:31
Please provide the steps to reproduce the issue.

**Comment by dougvan1701** [comment] 2023-02-19 21:47
I have this issue as well. It doesn't happen on every tile but I would say it happens about 20% of the time for me. 
As for reproducing the issue, it's random (to the best of my knowledge so far) when setting the priority of the depot. You'll see the the depot itself doesn't show the label but if you pan the camera down, you get the huge label that covers a significant portion of the screen.
Latest game version, Win10, latest nVidia drivers for my 3090ti, and the only mods I am using are depot priority, ore cell, endless resources, and more cities (but didn't add additional cities to this save).

I will add this: it is tile specific. If I have the problem with a tile, it will persist on that tile if I delete the depot and add it back.

**Comment by akarnokd** [comment] 2023-02-19 21:59
@dougvan1701 Could you please post the coordinates of the hex that's causing this issue (bottom status bar).

**Comment by dougvan1701** [comment] 2023-02-19 22:03
> 

Looks like Lat=84.8 Long=293.3
Screenshot attached that shows the error.
![DepotError](https://user-images.githubusercontent.com/96144777/219977818-711109b6-a70d-4086-add5-7aca7d0ebe9b.JPG)

**Comment by akarnokd** [comment] 2023-02-19 22:15
Thanks, I could reproduce the issue. I'll post a fix tomorrow. Until then, turn off the overlay numbers with <kbd>P</kbd> in those high altitudes.

**Comment by dougvan1701** [comment] 2023-02-19 22:52
> Thanks, I could reproduce the issue. I'll post a fix tomorrow. Until then, turn off the overlay numbers with P in those high altitudes.

Awesome. Thank you!

**Comment by akarnokd** [comment] 2023-02-20 09:24
Hey all. Thanks for the reports. This should now be fixed with the latest release (same bug was fixed in Disable Buildings too).

Let me know if it works for you now.

**Comment by Bryku1978** [comment] 2023-02-20 18:29
Thank you very much!!

**Closed as completed** 2023-02-20 18:29 UTC
Labels: more info needed
